# Generated by Django 5.1.4 on 2025-01-04 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('volume', models.IntegerField()),
                ('email', models.CharField(max_length=200)),
                ('detail', models.CharField(max_length=200)),
                ('phone', models.IntegerField()),
                ('subscribe', models.CharField(max_length=200)),
                ('dob', models.DateField()),
                ('gender', models.CharField(max_length=50)),
                ('resume', models.FileField(upload_to='')),
                ('profile_pic', models.FileField(upload_to='')),
            ],
        ),
    ]
